server:
  port: 0 # random port

spring:
  application:
    name: shop-service
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: default       # 사용할 프로파일
  elasticsearch:
    uris: http://localhost:9200
    connection-timeout: 1s
    socket-timeout: 3s
  cloud:
    config:
      fail-fast: true

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, info, prometheus
